all:
  hosts:
    example-host:
  vars:
    ansible_ssh_user: notroot
    ansible_ssh_private_key_file: "~/.ssh/notroot/id_rsa"
    ansible_python_interpreter: "/usr/bin/python3"
    base_install_dir: "/opt"
    default_user_shell: "/bin/bash"
    neural_style_dir: "{{ base_install_dir }}/neural_style"
